name: Laravel CI/CD Pipeline 🚀

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: task_tracker
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, xml, ctype, json, bcmath
          coverage: none

      - name: 📦 Install Composer dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist

      - name: ⚡ Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear
          php artisan cache:clear
        env:
          APP_ENV: testing
          APP_KEY: base64:RRl54JIknifPoBiGeQEhL1LvFgulvfTlGpTsHFbjTzE=
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: task_tracker
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: 🧱 Run database migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: task_tracker
          DB_USERNAME: root
          DB_PASSWORD: root

      - name: 🧪 Run Laravel tests
        run: php artisan test
