name: Laravel Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo_mysql

      # Step 3: Move into backend folder and install dependencies
      - name: Install Composer dependencies
        working-directory: ./backend
        run: composer install --no-progress --prefer-dist

      # Step 4: Copy example environment file
      - name: Copy .env
        working-directory: ./backend
        run: cp .env.example .env

      # Step 5: Generate app key
      - name: Generate application key
        working-directory: ./backend
        run: php artisan key:generate

      # Step 6: Run migrations
      - name: Run migrations
        working-directory: ./backend
        run: php artisan migrate --force || echo "Skipping migrations (no DB setup)"

      # Step 7: Run Laravel tests
      - name: Run Laravel tests
        working-directory: ./backend
        run: php artisan test
